@startuml first_idea

'skinparam linetype polyline
'skinparam linetype ortho

title Allowed dependencies

package Engine <<Rectangle>>{
}

package Events <<Rectangle>>{
}

package Functionality <<Rectangle>>{
}

package Data <<Database>>{
}

package Graphics <<Rectangle>>{
}

package "<<external>>\n    Unity" as Unity <<Cloud>>{
}

package "<<Facade>>\nMediator" as Meditator <<Rectangle>>{
}


class Main

'--------------------------------


Functionality --> Data : Read/Write
'Functionality --> Graphics
Functionality --> Meditator
Functionality --> Functionality

Main --> Data
Main --> Events

Graphics --> Unity

Events --> Functionality : Schedules
Events --> Engine
'Events --> Graphics : Injects callbacks

Engine --> Functionality : Executes

Meditator --> Graphics
Meditator --> Events

@enduml
'############################################################
'############################################################
'############################################################
@startuml mvc_architecture

title Allowed dependencies

package Graphics <<node>>{
    package Controller <<rectangle>>{
    }
    package View <<rectangle>>{
    }
    package Model <<Database>>{
    }
}

package User <<Cloud>>{
}

package Functionality <<node>>{
    package Service <<rectangle>>{
    }
    package SubService <<rectangle>>{
    }
    package Engine <<rectangle>>{
    }
}

package Data <<Database>>{
}

'--------------------------------

Controller "1" *--r-> "1" View : Update/Action
Controller "1" ---> "*" Service : Inject into\nEngine
Controller "*" ---> "1" Engine : Schedule\n&\nSetTimer

Model "1" <--l-* "1" Controller : Update
Model ...> Controller : answer

View ...> Controller : Event Callback
View <..l. User : Input
View ..l.> User : Graphics & Audio


Data <--l- Service : Read/Write
Data <--l- SubService : Read/Write

Service ...> Controller : Answer
Service "*" <--l-o "1" Engine : Execute
Service ...> Engine : Answer

SubService ...> Service : Answer
Service "1" *---> "*" SubService : Execute


@enduml
'############################################################
'############################################################
'############################################################
@startwbs folder_structure

title "Folder structure"

* Scripts
** Graphics
*** Gui
*** Entities
** Core 
*** Engine
*** Services
*** SubServices
** Data
** Utility

@endwbs