@startuml first_idea

'skinparam linetype polyline
'skinparam linetype ortho

title Allowed dependencies

package Engine <<Rectangle>>{
}

package Events <<Rectangle>>{
}

package Functionality <<Rectangle>>{
}

package Data <<Database>>{
}

package Graphics <<Rectangle>>{
}

package "<<external>>\n    Unity" as Unity <<Cloud>>{
}

package "<<Facade>>\nMediator" as Meditator <<Rectangle>>{
}


class Main

'--------------------------------


Functionality --> Data : Read/Write
'Functionality --> Graphics
Functionality --> Meditator
Functionality --> Functionality

Main --> Data
Main --> Events

Graphics --> Unity

Events --> Functionality : Schedules
Events --> Engine
'Events --> Graphics : Injects callbacks

Engine --> Functionality : Executes

Meditator --> Graphics
Meditator --> Events

@enduml
'############################################################
'############################################################
'############################################################
@startuml mvc_architecture

title Allowed dependencies

'!$GRAPHICS_COLOUR = "#D86C6C"
'!$OBJECT_COLOUR = "#D8C36C"
'!$FUNCTIONALITY_COLOUR = "#6CAFD8"

!$GRAPHICS_COLOUR = "#6CD8A8"
!$OBJECT_COLOUR = "#8DD86C"
!$FUNCTIONALITY_COLOUR = "#D8946C"

package Graphics <<node>> $GRAPHICS_COLOUR{

    package "  <<Singleton>>\n<b>Gui Manager" as GuiManager <<rectangle>>{
    }
    package "<b>Gui Register" as GuiRegister <<Database>>{
    }

    package Object <<frame>> $OBJECT_COLOUR{
            package "<b>Controller" as Controller <<rectangle>>{
            }
            package "<b>View" as View <<rectangle>>{
            }
            package "<b>Model" as Model <<Database>>{
        }
    }
}

package "<b>User" as User <<Cloud>>{
}

package Functionality <<node>> $FUNCTIONALITY_COLOUR{
    package "<b>Service" as Service <<rectangle>>{
    }
    package "<b>SubService" as SubService <<rectangle>>{
    }
    package "<<Singleton>>\n   <b>Engine" as Engine <<rectangle>>{
    }
}

package "<b>Data" as Data <<Database>>{
}

'--------------------------------

GuiRegister "1" o.d.> "*" Controller : Stores

GuiManager -l-> GuiRegister

Controller "1" *--r-> "1" View : Update/Action
Controller "1" ---> "*" Service : Inject into\nEngine
Controller "*" ---> "1" Engine : Schedule\n&\nSetTimer
Controller "*" -u-> "1" GuiManager : Access other\ncontrollers

Model "1" <--l-* "1" Controller : Update
Model ...> Controller : answer

View ...> Controller : Event Callback
View <..r. User : Input
View ..r.> User : Graphics & Audio

Data <--l- Service : Read/Write
Data <--l- SubService : Read/Write

Service ...> Controller : Answer
Service "*" <--l-o "1" Engine : Execute
Service ...> Engine : Answer

SubService ...> Service : Answer
Service "1" *---> "*" SubService : Execute






@enduml
'############################################################
'############################################################
'############################################################
@startwbs folder_structure

title "Folder structure"

* Scripts
** Graphics
*** Gui
*** Entities
** Core 
*** Engine
*** Services
*** SubServices
** Data
** Utility

@endwbs