USEA: usea.graphics.model.ExampleModel Class Reference
usea.graphics.model.ExampleModel Class Reference
Public Member Functions
void IncreaseCharge ()
void SetChargeIncrement (float newChargeIncrement)
void DecreaseCharge (float chargeDecrease)
float GetChargeRate ()
Private Attributes
float m_remainingCharge = 5
float m_chargeIncrement = 1
Static Private Attributes
const float MAX_CHARGE = 10
Detailed Description
Definition at line 8 of file ExampleModel.cs.
Member Function Documentation
DecreaseCharge()
void usea.graphics.model.ExampleModel.DecreaseCharge (float chargeDecrease)
Definition at line 21 of file ExampleModel.cs.
        {
            m_remainingCharge = Math.Max(0, m_remainingCharge - chargeDecrease);
        }
References usea.graphics.model.ExampleModel.m_remainingCharge.
Referenced by usea.graphics.controller.ExampleController.Update().
GetChargeRate()
float usea.graphics.model.ExampleModel.GetChargeRate ()
Definition at line 26 of file ExampleModel.cs.
        {
            return m_remainingCharge / MAX_CHARGE;
        }
References usea.graphics.model.ExampleModel.m_remainingCharge, and usea.graphics.model.ExampleModel.MAX_CHARGE.
Referenced by usea.graphics.controller.ExampleController.Initialize(), usea.graphics.controller.ExampleController.OnButtonPress(), and usea.graphics.controller.ExampleController.Update().
IncreaseCharge()
void usea.graphics.model.ExampleModel.IncreaseCharge ()
Definition at line 11 of file ExampleModel.cs.
        {
            m_remainingCharge = Math.Min(MAX_CHARGE, m_remainingCharge + m_chargeIncrement);
        }
References usea.graphics.model.ExampleModel.m_chargeIncrement, usea.graphics.model.ExampleModel.m_remainingCharge, and usea.graphics.model.ExampleModel.MAX_CHARGE.
Referenced by usea.graphics.controller.ExampleController.OnButtonPress().
SetChargeIncrement()
void usea.graphics.model.ExampleModel.SetChargeIncrement (float newChargeIncrement)
Definition at line 16 of file ExampleModel.cs.
        {
            m_chargeIncrement = newChargeIncrement;
        }
References usea.graphics.model.ExampleModel.m_chargeIncrement.
Referenced by usea.graphics.controller.ExampleController.Initialize().
Member Data Documentation
m_chargeIncrement
float usea.graphics.model.ExampleModel.m_chargeIncrement = 1 private
Definition at line 34 of file ExampleModel.cs.
Referenced by usea.graphics.model.ExampleModel.IncreaseCharge(), and usea.graphics.model.ExampleModel.SetChargeIncrement().
m_remainingCharge
float usea.graphics.model.ExampleModel.m_remainingCharge = 5 private
Definition at line 33 of file ExampleModel.cs.
Referenced by usea.graphics.model.ExampleModel.DecreaseCharge(), usea.graphics.model.ExampleModel.GetChargeRate(), and usea.graphics.model.ExampleModel.IncreaseCharge().
MAX_CHARGE
const float usea.graphics.model.ExampleModel.MAX_CHARGE = 10 static private
Definition at line 32 of file ExampleModel.cs.
Referenced by usea.graphics.model.ExampleModel.GetChargeRate(), and usea.graphics.model.ExampleModel.IncreaseCharge().
The documentation for this class was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Graphics/ExampleMenu/ExampleModel.cs