USEA: usea.graphics.gui.EventEnabled Class Reference
usea.graphics.gui.EventEnabled Class Reference abstract
Base class for gui objects that should use Unity events.
Classes
struct Callbacks
Public Member Functions
delegate void Callback ()
EventEnabled ()
void AddOnPointerClickCallback (Callback callback)
void AddOnPointerEnterCallback (Callback callback)
void AddOnPointerExitCallback (Callback callback)
void AddOnPointerDownCallback (Callback callback)
void AddOnPointerUpCallback (Callback callback)
void OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerEnter (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerExit (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerUp (UnityEngine.EventSystems.PointerEventData eventData)
Private Attributes
Callbacks m_callbacks = new Callbacks()
Detailed Description
Base class for gui objects that should use Unity events.
Definition at line 13 of file EventEnabled.cs.
Constructor & Destructor Documentation
EventEnabled()
usea.graphics.gui.EventEnabled.EventEnabled ()
Definition at line 24 of file EventEnabled.cs.
        {
            /*
            m_callbacks = new Dictionary<EventTypeE, Callback>() {{EventTypeE.ON_POINTER_CLICK, null},
                                                                  {EventTypeE.ON_POINTER_ENTER, null},
                                                                  {EventTypeE.ON_POINTER_EXIT, null},
                                                                  {EventTypeE.ON_POINTER_DOWN, null},
                                                                  {EventTypeE.ON_POINTER_UP, null}};
            */
        }
Member Function Documentation
AddOnPointerClickCallback()
void usea.graphics.gui.EventEnabled.AddOnPointerClickCallback (Callback callback)
Definition at line 35 of file EventEnabled.cs.
        {
            m_callbacks.onPointerClick += callback;
            //m_callbacks[EventTypeE.ON_POINTER_CLICK] = callback;
        }
AddOnPointerDownCallback()
void usea.graphics.gui.EventEnabled.AddOnPointerDownCallback (Callback callback)
Definition at line 53 of file EventEnabled.cs.
        {
            m_callbacks.onPointerDown += callback;
            //m_callbacks[EventTypeE.ON_POINTER_DOWN] = callback;
        }
Referenced by usea.graphics.gui.Button.SetColourListeners().
AddOnPointerEnterCallback()
void usea.graphics.gui.EventEnabled.AddOnPointerEnterCallback (Callback callback)
Definition at line 41 of file EventEnabled.cs.
        {
            m_callbacks.onPointerEnter += callback;
            //m_callbacks[EventTypeE.ON_POINTER_ENTER] = callback;
        }
Referenced by usea.graphics.gui.Button.SetColourListeners().
AddOnPointerExitCallback()
void usea.graphics.gui.EventEnabled.AddOnPointerExitCallback (Callback callback)
Definition at line 47 of file EventEnabled.cs.
        {
            m_callbacks.onPointerExit += callback;
            //m_callbacks[EventTypeE.ON_POINTER_EXIT] = callback;
        }
Referenced by usea.graphics.gui.Button.SetColourListeners().
AddOnPointerUpCallback()
void usea.graphics.gui.EventEnabled.AddOnPointerUpCallback (Callback callback)
Definition at line 59 of file EventEnabled.cs.
        {
            m_callbacks.onPointerUp += callback;
            //m_callbacks[EventTypeE.ON_POINTER_UP] = callback;
        }
Referenced by usea.graphics.gui.Button.SetColourListeners().
Callback()
delegate void usea.graphics.gui.EventEnabled.Callback ()
OnPointerClick()
void usea.graphics.gui.EventEnabled.OnPointerClick (UnityEngine::EventSystems::PointerEventData eventData)
Definition at line 65 of file EventEnabled.cs.
        {
            m_callbacks.OnPointerClick();
            //m_callbacks[EventTypeE.ON_POINTER_CLICK]?.Invoke();
        }
References usea.graphics.gui.EventEnabled.m_callbacks, and usea.graphics.gui.EventEnabled.Callbacks.OnPointerClick().
OnPointerDown()
void usea.graphics.gui.EventEnabled.OnPointerDown (UnityEngine::EventSystems::PointerEventData eventData)
Definition at line 83 of file EventEnabled.cs.
        {
            m_callbacks.OnPointerDown();
            //m_callbacks[EventTypeE.ON_POINTER_DOWN]?.Invoke();
        }
References usea.graphics.gui.EventEnabled.m_callbacks, and usea.graphics.gui.EventEnabled.Callbacks.OnPointerDown().
OnPointerEnter()
void usea.graphics.gui.EventEnabled.OnPointerEnter (UnityEngine::EventSystems::PointerEventData eventData)
Definition at line 71 of file EventEnabled.cs.
        {
            m_callbacks.OnPointerEnter();
            //m_callbacks[EventTypeE.ON_POINTER_ENTER]?.Invoke();
        }
References usea.graphics.gui.EventEnabled.m_callbacks, and usea.graphics.gui.EventEnabled.Callbacks.OnPointerEnter().
OnPointerExit()
void usea.graphics.gui.EventEnabled.OnPointerExit (UnityEngine::EventSystems::PointerEventData eventData)
Definition at line 77 of file EventEnabled.cs.
        {
            m_callbacks.OnPointerExit();
            //m_callbacks[EventTypeE.ON_POINTER_EXIT]?.Invoke();
        }
References usea.graphics.gui.EventEnabled.m_callbacks, and usea.graphics.gui.EventEnabled.Callbacks.OnPointerExit().
OnPointerUp()
void usea.graphics.gui.EventEnabled.OnPointerUp (UnityEngine::EventSystems::PointerEventData eventData)
Definition at line 89 of file EventEnabled.cs.
        {
            m_callbacks.OnPointerUp();
            //m_callbacks[EventTypeE.ON_POINTER_UP]?.Invoke();
        }
References usea.graphics.gui.EventEnabled.m_callbacks, and usea.graphics.gui.EventEnabled.Callbacks.OnPointerUp().
Member Data Documentation
m_callbacks
Callbacks usea.graphics.gui.EventEnabled.m_callbacks = new Callbacks() private
Definition at line 121 of file EventEnabled.cs.
Referenced by usea.graphics.gui.EventEnabled.OnPointerClick(), usea.graphics.gui.EventEnabled.OnPointerDown(), usea.graphics.gui.EventEnabled.OnPointerEnter(), usea.graphics.gui.EventEnabled.OnPointerExit(), and usea.graphics.gui.EventEnabled.OnPointerUp().
The documentation for this class was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Graphics/Gui/EventEnabled.cs