USEA: usea.graphics.controller.Controller Class Reference
usea.graphics.controller.Controller Class Reference abstract
Base class for all coordinators/controllers in a mvc (Model, View, Controller) triplet.
Public Member Functions
partial void OnEnable ()
partial void OnDisable ()
partial void OnEnable ()
partial void OnDisable ()
Protected Member Functions
void Initialize ()
Used for settings callbacks for all owned gui objects.
void Show ()
void Hide ()
Private Attributes
bool m_isInitialized
GuiObjectTypeE m_name
Detailed Description
Base class for all coordinators/controllers in a mvc (Model, View, Controller) triplet.
Definition at line 9 of file Controller.cs.
Member Function Documentation
Hide()
void usea.graphics.controller.Controller.Hide () abstract protected
Referenced by usea.graphics.controller.Controller.OnDisable().
Initialize()
void usea.graphics.controller.Controller.Initialize () abstract protected
Used for settings callbacks for all owned gui objects.
Referenced by usea.graphics.controller.Controller.OnEnable().
OnDisable() [1/2]
partial void usea.graphics.controller.Controller.OnDisable ()
OnDisable() [2/2]
partial void usea.graphics.controller.Controller.OnDisable ()
Definition at line 42 of file Controller.cs.
        {
            Hide();
        }
References usea.graphics.controller.Controller.Hide().
OnEnable() [1/2]
partial void usea.graphics.controller.Controller.OnEnable ()
OnEnable() [2/2]
partial void usea.graphics.controller.Controller.OnEnable ()
Definition at line 30 of file Controller.cs.
        {
            if (!m_isInitialized)
            {
                m_isInitialized = true;
                Initialize();
                GuiManager.Get().RegisterObject(m_name, this);
            }
            Show();
        }
References usea.graphics.GuiManager.Get(), usea.graphics.controller.Controller.Initialize(), usea.graphics.controller.Controller.m_isInitialized, usea.graphics.controller.Controller.m_name, usea.graphics.GuiManager.RegisterObject(), and usea.graphics.controller.Controller.Show().
Show()
void usea.graphics.controller.Controller.Show () abstract protected
Referenced by usea.graphics.controller.Controller.OnEnable().
Member Data Documentation
m_isInitialized
bool usea.graphics.controller.Controller.m_isInitialized private
Definition at line 24 of file Controller.cs.
Referenced by usea.graphics.controller.Controller.OnEnable().
m_name
GuiObjectTypeE usea.graphics.controller.Controller.m_name private
Definition at line 25 of file Controller.cs.
Referenced by usea.graphics.controller.Controller.OnEnable().
The documentation for this class was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Graphics/Controller.cs