USEA: usea.graphics.gui.Button Class Reference
usea.graphics.gui.Button Class Reference
A custom implementation of a button. Has more flexible callbacks than Unity's default button implementation.
Classes
struct ColourSettings
Public Member Functions
partial void Awake ()
partial void SetTooltip (string message)
partial void Awake ()
partial void SetTooltip (string message)
Public Member Functions inherited from usea.graphics.gui.EventEnabled
void AddOnPointerClickCallback (util.types.Callback callback)
void AddOnPointerEnterCallback (util.types.Callback callback)
void AddOnPointerExitCallback (util.types.Callback callback)
void AddOnPointerDownCallback (util.types.Callback callback)
void AddOnPointerUpCallback (util.types.Callback callback)
void OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerEnter (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerExit (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData)
void OnPointerUp (UnityEngine.EventSystems.PointerEventData eventData)
Private Member Functions
partial void SetColourListeners ()
partial void SetColourListeners ()
Private Attributes
ColourSettings m_boxColour
ColourSettings m_textColour
Image m_image
TMP_Text m_text
bool m_isCursorOnThisObject
Detailed Description
A custom implementation of a button. Has more flexible callbacks than Unity's default button implementation.
@TODO: SetSoundListener functionality @TODO: SetImage functionality
Definition at line 14 of file Button.cs.
Member Function Documentation
Awake() [1/2]
partial void usea.graphics.gui.Button.Awake ()
Awake() [2/2]
partial void usea.graphics.gui.Button.Awake ()
Definition at line 42 of file Button.cs.
        {
            m_isCursorOnThisObject = false;
            //SetSoundListeners();
            //SetTooltipListeners();
            SetColourListeners();
        }
References usea.graphics.gui.Button.m_isCursorOnThisObject, and usea.graphics.gui.Button.SetColourListeners().
SetColourListeners() [1/2]
partial void usea.graphics.gui.Button.SetColourListeners () private
Referenced by usea.graphics.gui.Button.Awake().
SetColourListeners() [2/2]
partial void usea.graphics.gui.Button.SetColourListeners () private
Definition at line 65 of file Button.cs.
        {
            AddOnPointerEnterCallback(() =>
            {
                m_isCursorOnThisObject = true;
                m_image.color = m_boxColour.onPointerEnter;
                m_text.color = m_textColour.onPointerEnter;
            });
            AddOnPointerExitCallback(() =>
            {
                m_isCursorOnThisObject = false;
                m_image.color = m_boxColour.normal;
                m_text.color = m_textColour.normal;
            });
            AddOnPointerDownCallback(() =>
            {
                m_image.color = m_boxColour.onPointerClick;
                m_text.color = m_textColour.onPointerClick;
            });
            AddOnPointerUpCallback(() =>
            {
                m_image.color = m_isCursorOnThisObject ? m_boxColour.onPointerEnter : m_boxColour.normal;
                m_text.color = m_isCursorOnThisObject ? m_textColour.onPointerEnter : m_textColour.normal;
            });
        }
References usea.graphics.gui.EventEnabled.AddOnPointerDownCallback(), usea.graphics.gui.EventEnabled.AddOnPointerEnterCallback(), usea.graphics.gui.EventEnabled.AddOnPointerExitCallback(), usea.graphics.gui.EventEnabled.AddOnPointerUpCallback(), usea.graphics.gui.Button.m_boxColour, usea.graphics.gui.Button.m_isCursorOnThisObject, usea.graphics.gui.Button.m_textColour, usea.graphics.gui.Button.ColourSettings.normal, usea.graphics.gui.Button.ColourSettings.onPointerClick, and usea.graphics.gui.Button.ColourSettings.onPointerEnter.
SetTooltip() [1/2]
partial void usea.graphics.gui.Button.SetTooltip (string message)
SetTooltip() [2/2]
partial void usea.graphics.gui.Button.SetTooltip (string message)
Definition at line 50 of file Button.cs.
        {
            AddOnPointerEnterCallback(() =>
            {
                TooltipController a = (TooltipController)GuiManager.Get().GetObject(GuiObjectTypeE.TOOLTIP);
                a.Activate(message);
            });
            AddOnPointerExitCallback(() =>
            {
                TooltipController a = (TooltipController)GuiManager.Get().GetObject(GuiObjectTypeE.TOOLTIP);
                a.Deactivate();
            });
        }
References usea.graphics.controller.TooltipController.Activate(), usea.graphics.gui.EventEnabled.AddOnPointerEnterCallback(), usea.graphics.gui.EventEnabled.AddOnPointerExitCallback(), usea.graphics.controller.TooltipController.Deactivate(), usea.graphics.GuiManager.Get(), and usea.graphics.GuiManager.GetObject().
Member Data Documentation
m_boxColour
ColourSettings usea.graphics.gui.Button.m_boxColour private
Definition at line 31 of file Button.cs.
Referenced by usea.graphics.gui.Button.SetColourListeners().
m_image
Image usea.graphics.gui.Button.m_image private
Definition at line 35 of file Button.cs.
m_isCursorOnThisObject
bool usea.graphics.gui.Button.m_isCursorOnThisObject private
Definition at line 37 of file Button.cs.
Referenced by usea.graphics.gui.Button.Awake(), and usea.graphics.gui.Button.SetColourListeners().
m_text
TMP_Text usea.graphics.gui.Button.m_text private
Definition at line 36 of file Button.cs.
m_textColour
ColourSettings usea.graphics.gui.Button.m_textColour private
Definition at line 32 of file Button.cs.
Referenced by usea.graphics.gui.Button.SetColourListeners().
The documentation for this class was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Graphics/Gui/Button.cs