USEA: usea.graphics.controller.ExampleController Class Reference
usea.graphics.controller.ExampleController Class Reference
Public Member Functions
partial void Update ()
partial void Update ()
Public Member Functions inherited from usea.graphics.controller.Controller
partial void OnEnable ()
partial void OnDisable ()
partial void OnEnable ()
partial void OnDisable ()
Protected Member Functions
override partial void Initialize ()
override partial void Show ()
override partial void Hide ()
override partial void Initialize ()
override partial void Show ()
override partial void Hide ()
Protected Member Functions inherited from usea.graphics.controller.Controller
void Initialize ()
Used for settings callbacks for all owned gui objects.
void Show ()
void Hide ()
Private Member Functions
partial void OnButtonPress ()
partial void OnButtonPress ()
Private Attributes
ExampleModel m_model
ExampleView m_view
Detailed Description
Definition at line 11 of file ExampleController.cs.
Member Function Documentation
Hide() [1/2]
override partial void usea.graphics.controller.ExampleController.Hide () protected
Hide() [2/2]
override partial void usea.graphics.controller.ExampleController.Hide () protected
Definition at line 51 of file ExampleController.cs.
        {
            print("Hide");
        }
Initialize() [1/2]
override partial void usea.graphics.controller.ExampleController.Initialize () protected
Initialize() [2/2]
override partial void usea.graphics.controller.ExampleController.Initialize () protected
Definition at line 35 of file ExampleController.cs.
        {
            print("Initialize");
            m_model.SetChargeIncrement(1);
            m_view.m_button.AddOnPointerClickCallback(OnButtonPress);
            m_view.m_toggle.SetOnCallback(() => { m_model.SetChargeIncrement(3); });
            m_view.m_toggle.SetOffCallback(() => { m_model.SetChargeIncrement(1); });
            //m_view.m_toggle.SetTooltip("On: Increment=3\nOff: Increment=1");
            m_view.m_slider.value = m_model.GetChargeRate();
        }
References usea.graphics.model.ExampleModel.GetChargeRate(), usea.graphics.view.ExampleView.m_button, usea.graphics.controller.ExampleController.m_model, usea.graphics.view.ExampleView.m_toggle, usea.graphics.controller.ExampleController.m_view, usea.graphics.controller.ExampleController.OnButtonPress(), and usea.graphics.model.ExampleModel.SetChargeIncrement().
OnButtonPress() [1/2]
partial void usea.graphics.controller.ExampleController.OnButtonPress () private
Referenced by usea.graphics.controller.ExampleController.Initialize().
OnButtonPress() [2/2]
partial void usea.graphics.controller.ExampleController.OnButtonPress () private
Definition at line 56 of file ExampleController.cs.
        {
            print("OnButtonPress");
            m_model.IncreaseCharge();
            m_view.m_slider.value = m_model.GetChargeRate();
        }
References usea.graphics.model.ExampleModel.GetChargeRate(), usea.graphics.model.ExampleModel.IncreaseCharge(), and usea.graphics.controller.ExampleController.m_model.
Show() [1/2]
override partial void usea.graphics.controller.ExampleController.Show () protected
Show() [2/2]
override partial void usea.graphics.controller.ExampleController.Show () protected
Definition at line 46 of file ExampleController.cs.
        {
            print("Show");
        }
Update() [1/2]
partial void usea.graphics.controller.ExampleController.Update ()
Update() [2/2]
partial void usea.graphics.controller.ExampleController.Update ()
Definition at line 29 of file ExampleController.cs.
        {
            m_model.DecreaseCharge(Time.deltaTime);
            m_view.m_slider.value = m_model.GetChargeRate();
        }
References usea.graphics.model.ExampleModel.DecreaseCharge(), usea.graphics.model.ExampleModel.GetChargeRate(), and usea.graphics.controller.ExampleController.m_model.
Member Data Documentation
m_model
ExampleModel usea.graphics.controller.ExampleController.m_model private
Definition at line 23 of file ExampleController.cs.
Referenced by usea.graphics.controller.ExampleController.Initialize(), usea.graphics.controller.ExampleController.OnButtonPress(), and usea.graphics.controller.ExampleController.Update().
m_view
ExampleView usea.graphics.controller.ExampleController.m_view private
Definition at line 24 of file ExampleController.cs.
Referenced by usea.graphics.controller.ExampleController.Initialize().
The documentation for this class was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Graphics/ExampleMenu/ExampleController.cs