USEA: usea.Main Class Reference
usea.Main Class Reference
Some main classie.
Public Member Functions
Main ()
Private Member Functions
void initializeStuff ()
Private Attributes
EventExample m_eventExample
Detailed Description
Some main classie.
Definition at line 16 of file Main.cs.
Constructor & Destructor Documentation
Main()
usea.Main.Main ()
Definition at line 19 of file Main.cs.
        {
            initializeStuff();
        }
References usea.Main.initializeStuff().
Member Function Documentation
initializeStuff()
void usea.Main.initializeStuff () private
Definition at line 24 of file Main.cs.
        {
            m_eventExample = new EventExample();
            m_eventExample.initialize();
            Database.initialize();
        }
References usea.data.Database.initialize(), usea.events.EventExample.initialize(), and usea.Main.m_eventExample.
Referenced by usea.Main.Main().
Member Data Documentation
m_eventExample
EventExample usea.Main.m_eventExample private
Definition at line 32 of file Main.cs.
Referenced by usea.Main.initializeStuff().
The documentation for this class was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Main/Main.cs