USEA: usea.graphics.gui.EventEnabled.Callbacks Struct Reference
usea.graphics.gui.EventEnabled.Callbacks Struct Reference
Public Member Functions
void OnPointerClick ()
void OnPointerEnter ()
void OnPointerExit ()
void OnPointerDown ()
void OnPointerUp ()
Events
util.types.Callback onPointerClick
util.types.Callback onPointerEnter
util.types.Callback onPointerExit
util.types.Callback onPointerDown
util.types.Callback onPointerUp
Detailed Description
Definition at line 93 of file EventEnabled.cs.
Member Function Documentation
OnPointerClick()
void usea.graphics.gui.EventEnabled.Callbacks.OnPointerClick ()
Definition at line 100 of file EventEnabled.cs.
{ onPointerClick?.Invoke(); }
References usea.graphics.gui.EventEnabled.Callbacks.onPointerClick.
Referenced by usea.graphics.gui.EventEnabled.OnPointerClick().
OnPointerDown()
void usea.graphics.gui.EventEnabled.Callbacks.OnPointerDown ()
Definition at line 103 of file EventEnabled.cs.
{ onPointerDown?.Invoke(); }
References usea.graphics.gui.EventEnabled.Callbacks.onPointerDown.
Referenced by usea.graphics.gui.EventEnabled.OnPointerDown().
OnPointerEnter()
void usea.graphics.gui.EventEnabled.Callbacks.OnPointerEnter ()
Definition at line 101 of file EventEnabled.cs.
{ onPointerEnter?.Invoke(); }
References usea.graphics.gui.EventEnabled.Callbacks.onPointerEnter.
Referenced by usea.graphics.gui.EventEnabled.OnPointerEnter().
OnPointerExit()
void usea.graphics.gui.EventEnabled.Callbacks.OnPointerExit ()
Definition at line 102 of file EventEnabled.cs.
{ onPointerExit?.Invoke(); }
References usea.graphics.gui.EventEnabled.Callbacks.onPointerExit.
Referenced by usea.graphics.gui.EventEnabled.OnPointerExit().
OnPointerUp()
void usea.graphics.gui.EventEnabled.Callbacks.OnPointerUp ()
Definition at line 104 of file EventEnabled.cs.
{ onPointerUp?.Invoke(); }
References usea.graphics.gui.EventEnabled.Callbacks.onPointerUp.
Referenced by usea.graphics.gui.EventEnabled.OnPointerUp().
Event Documentation
onPointerClick
util.types.Callback usea.graphics.gui.EventEnabled.Callbacks.onPointerClick
Definition at line 95 of file EventEnabled.cs.
Referenced by usea.graphics.gui.EventEnabled.Callbacks.OnPointerClick().
onPointerDown
util.types.Callback usea.graphics.gui.EventEnabled.Callbacks.onPointerDown
Definition at line 98 of file EventEnabled.cs.
Referenced by usea.graphics.gui.EventEnabled.Callbacks.OnPointerDown().
onPointerEnter
util.types.Callback usea.graphics.gui.EventEnabled.Callbacks.onPointerEnter
Definition at line 96 of file EventEnabled.cs.
Referenced by usea.graphics.gui.EventEnabled.Callbacks.OnPointerEnter().
onPointerExit
util.types.Callback usea.graphics.gui.EventEnabled.Callbacks.onPointerExit
Definition at line 97 of file EventEnabled.cs.
Referenced by usea.graphics.gui.EventEnabled.Callbacks.OnPointerExit().
onPointerUp
util.types.Callback usea.graphics.gui.EventEnabled.Callbacks.onPointerUp
Definition at line 99 of file EventEnabled.cs.
Referenced by usea.graphics.gui.EventEnabled.Callbacks.OnPointerUp().
The documentation for this struct was generated from the following file:
C:/Users/armem/OneDrive/Dokumente/Projects/UntitledSurvivalExploration/Assets/Scripts/Graphics/Gui/EventEnabled.cs