@startuml Scene_Transitions

title Scene transitions

state MainMenu
state NewGameMenu
state About
state GameSession
state Settings

hide empty description

'  -> horizontal
' --> vertical

[*] --> MainMenu : Start

MainMenu -l-> About
About -r-> MainMenu

MainMenu -r-> Settings
MainMenu --> NewGameMenu
MainMenu -u-> [*] : Exit

NewGameMenu -> GameSession
NewGameMenu --> MainMenu
NewGameMenu --> Settings

GameSession --> Settings
GameSession -> MainMenu
GameSession -u-> [*] : Exit

Settings -> MainMenu
Settings -> GameSession
Settings -> NewGameMenu

@enduml